### ISSUE TITLE
Feature Request: Editing Waypoints

### ISSUE THREAD

**Issue by bdaroz** [vannaka/Motion_Profile_Generator#1]
When mapping out a path, you may want to alter or change a waypoint without clearing the entire list. Make the list selectable and re-populate the "Add" boxes with the selected values (change the "Add" button to "Update") and return to normal when the update is committed.

**Comment by blake1029384756** [comment]
@bdaroz Thank you for the request. I really like the idea and will get that implemented within a few days.

**Comment by blake1029384756** [comment]
@bdaroz I have added your requested feature. Thanks for the feedback!
