### ISSUE TITLE
How to set wheel radius to get accurate positions in rotations in the generated CSV?

### ISSUE THREAD

**Issue by Covmon** [vannaka/Motion_Profile_Generator#10]
I'm not sure how the program can generate data for number of rotations (the position column in the CSV) without knowing the diameter and thus circumference of the wheels used. If a larger wheel is used, then it will take fewer rotations to reach the target position. Does the program assume a certain wheel diameter/circumference? We are using 6'' wheels. Thanks for the great program though!

**Comment by vannaka** [comment]
The output data is in feet/meters. This means you'll have to do the unit conversions in your code before you send the points to the talons.

**Comment by Covmon** [comment]
Yes, I did know that. Thanks for the help.
