### ISSUE TITLE
Robot Driving in Reverse

### ISSUE THREAD

**Issue by Covmon** [vannaka/Motion_Profile_Generator#12]

**Comment by vannaka** [comment]
This is a robot code problem not ours. Try inverting each side of the drive train.

**Comment by Covmon** [comment]
I'm not sure it's possible to invert the drive train in the middle of a motion profile, but it's worth looking into. Thanks.

**Comment by blake1029384756** [comment]
Jacis library hasn't implemented the ability to generate a path in reverse after going forward. To go backwards you could generate a second profile and run it right after the first.

 The backwards profile will have the sides inverted or swap the csv's. The left file becomes the right and the right become the left.

**Comment by Covmon** [comment]
Yeah, that’s what I was thinking. I can generate separate profiles for the reverse and forward parts, and invert the motors before the reverse part (switching left and right as well) and then invert them back before the forward part. Thanks for the advice.
