### ISSUE TITLE
Add docs

### ISSUE THREAD

**Issue by Ewpratten** [vannaka/Motion_Profile_Generator#14]
I am currently trying to work with this program and have exported the files. But I can't figure out what to do with them to move the robot. This is c++ btw.

**Comment by vannaka** [comment]
Hi @Ewpratten, this program is only meant to generate paths for the robot to follow. There are many different ways to actually follow these paths. The easiest is to use the built-in feature of TalonSRX's called MotionProfiles. Check out it's documentation [here](https://github.com/CrossTheRoadElec/Phoenix-Documentation/blob/master/Talon%20SRX%20Motion%20Profile%20Reference%20Manual.pdf).
