### ISSUE TITLE
Feature Request: Saving profiles

### ISSUE THREAD

**Issue by firecrafty** [vannaka/Motion_Profile_Generator#2]
It would be nice if users could save a profile so that they could edit it later, rather than having to remember and reenter all of the waypoints and settings.

**Comment by blake1029384756** [comment]
I have added this feature in the [1.2.0](https://github.com/vannaka/Motion_Profile_Generator/releases/tag/v1.2.0) release! The readme has been updated to reflect the changes. Comment here if you have any further questions.
