### ISSUE TITLE
[Enhancement] Units in inches

### ISSUE THREAD

**Issue by codeNinjaDev** [vannaka/Motion_Profile_Generator#22]
It would be really nice if there was a choice of units in inches. I started one here, but is really buggy: https://github.com/codeNinjaDev/Motion_Profile_Generator

**Comment by vannaka** [comment]
Can you make a good case for inches? Why not just use feet and convert your measurements from inches?

**Comment by codeNinjaDev** [comment]
It's probably the most convenient because it is used by a measuring tape.

**Comment by codeNinjaDev** [comment]
You are right I can convert it, but I thought it might be easier
