### ISSUE TITLE
Talon Export Mode velocity should be in RPM

### ISSUE THREAD

**Issue by TahsinAhmed13** [vannaka/Motion_Profile_Generator#32]
CTRE's talon motion profile mode takes velocity in RPM and not in units/sec like Jaci's Pathfinder, so a conversion in the Talon export mode would be helpful.

**Comment by vannaka** [comment]
While in mp mode the talons want the velocity in Units/100ms not RPM. We chose to only output in units/sec to accommodate for various wheel diameters. Why not just do the conversion as you're loading the csv?
