### ISSUE TITLE
Saving Files as xml not working

### ISSUE THREAD

**Issue by idanshulman** [vannaka/Motion_Profile_Generator#34]
I ran the command gradlew build, and the application starts as expected and works well.
The problem is when I try to save the profile as XML, I click save but the file is not saved at all and nothing happens.

**Comment by blake1029384756** [comment]
@idanshulman if you havent saved the project before you will have to "save as" and then subsequent saves will be will just "save"

**Comment by idanshulman** [comment]
Hey, I did try saving as the project, this is when the problem occurs. When ai click save as, no xml file is actually saved.

**Comment by blake1029384756** [comment]
Hmm. What OS are you using? Does your current user have write permissions on the folder?

**Comment by idanshulman** [comment]
I am administrator using Windows 10

**Comment by blake1029384756** [comment]
This is weird, it was working for me and then I just tried it again and the same thing happened.

**Comment by blake1029384756** [comment]
Okay so I have looked into this today and found that the working directory was stuck to where I originally ran the app even after I moved the app to a different folder. The original directory where I ran the app did not exist anymore so nothing happened when I clicked save. I confirmed this by creating the missing directory and the save option started working again. 

To check where your working directory is, open .../users/user/.motion-profile-generator/mpg.properties in a text editor and look at the value of file.workingDir. You can also change this value to the directory where your app is.

I think the main problem was that the original directory didnt exist anymore.

**Comment by idanshulman** [comment]
Thanks for the reply @blake1029384756 , I tried changing the file.workingDir attribute of the properties file and noticed it changes automatically to the correct value. I ran the jar from the cmd and received an exception when clicking the save button on the save as windows, and the exception occurs on every working directory.

The unhandled exception:

> Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
>         at javafx.fxml/javafx.fxml.FXMLLoader$MethodHandler.invoke(Unknown Source)
>         at javafx.fxml/javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(Unknown Source)
>         at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
>         at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
>         at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
>         at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
>         at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
>         at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
>         at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
>         at javafx.base/javafx.event.Event.fireEvent(Unknown Source)
>         at javafx.controls/javafx.scene.control.MenuItem.fire(Unknown Source)
>         at javafx.controls/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(Unknown Source)
>         at javafx.controls/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(Unknown Source)
>         at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
>         at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
>         at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
>         at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
>         at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
>         at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
>         at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
>         at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
>         at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
>         at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
>         at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
>         at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
>         at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
>         at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
>         at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
>         at javafx.base/javafx.event.Event.fireEvent(Unknown Source)
>         at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Unknown Source)
>         at javafx.graphics/javafx.scene.Scene$MouseHandler.access$1300(Unknown Source)
>         at javafx.graphics/javafx.scene.Scene.processMouseEvent(Unknown Source)
>         at javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
>         at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
>         at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
>         at java.base/java.security.AccessController.doPrivileged(Native Method)
>         at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
>         at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
>         at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
>         at javafx.graphics/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
>         at javafx.graphics/com.sun.glass.ui.View.notifyMouse(Unknown Source)
>         at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
>         at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
>         at java.base/java.lang.Thread.run(Unknown Source)
> Caused by: java.lang.reflect.InvocationTargetException
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>         at java.base/java.lang.reflect.Method.invoke(Unknown Source)
>         at com.sun.javafx.reflect.Trampoline.invoke(Unknown Source)
>         at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>         at java.base/java.lang.reflect.Method.invoke(Unknown Source)
>         at javafx.base/com.sun.javafx.reflect.MethodUtil.invoke(Unknown Source)
>         at javafx.fxml/com.sun.javafx.fxml.MethodHelper.invoke(Unknown Source)
>         ... 44 more
> Caused by: java.lang.NoSuchMethodError: com.sun.org.apache.xml.internal.serialize.OutputFormat.<init>(Lorg/w3c/dom/Document;)V
>         at com.mammen.main.ProfileGenerator.saveWorkingProject(ProfileGenerator.java:435)
>         at com.mammen.main.ProfileGenerator.saveProjectAs(ProfileGenerator.java:386)
>         at com.mammen.ui.javafx.MainUIController.showSaveAsDialog(MainUIController.java:480)
>         ... 54 more

**Comment by blake1029384756** [comment]
@idanshulman Can you please built from the latest code and try again? A java update a few days ago removed the old xml library. The following line makes me think you have the old code:
Caused by: java.lang.NoSuchMethodError: com.sun.org.apache.xml.internal.serialize.OutputFormat.(Lorg/w3c/dom/Document;)V

**Comment by idanshulman** [comment]
Thanks, That solved my problem

**Comment by blake1029384756** [comment]
Awesome good to hear!
