### ISSUE TITLE
Window size issues

### ISSUE THREAD

**Issue by blake1029384756** [vannaka/Motion_Profile_Generator#35]
As reported by @DisplayedAim in issue #33 

Well the file & help bar options aren't appearing and I'm not sure why :/ 
![capture](https://user-images.githubusercontent.com/33333386/42982641-9012015c-8c25-11e8-951e-d8efa7da039f.PNG)

**Comment by Raptorofwar** [comment]
Same issue still pops up.
![problemwithpathfinder](https://user-images.githubusercontent.com/42446863/44691633-49dba780-aa14-11e8-8ce5-866132dbeda3.PNG)

**Comment by vannaka** [comment]
Is this with the latest code on the Dev branch?

**Comment by vannaka** [comment]
./gradlew build

The outputted jar will be in build/libs

**Comment by Raptorofwar** [comment]
Thanks. Worked.
