### ISSUE TITLE
Background Image ratio 

### ISSUE THREAD

**Issue by Leo428** [vannaka/Motion_Profile_Generator#37]
This is more of a question than a bug. I want to load a vex field into the program. What code do I need to change to make the ratio of the image panel 1:1 since it is currently 32:27 ration? Thank you for answering!

**Comment by blake1029384756** [comment]
@Leo428  If you change the scale on the x and y to be the same it will be a 1:1 ratio

**Comment by Leo428** [comment]
Thanks, do I just change this line? Sorry that I am not familiar with JavaFX. Thanks for helping! 
https://github.com/vannaka/Motion_Profile_Generator/blob/b83a26b99442de539d15cf94119e50da23f030a8/src/com/mammen/ui/javafx/MainUI.fxml#L207

**Comment by blake1029384756** [comment]
In src/com/mammen/ui/javafx/MainUIController.java inside updateChartAxis() change:
AxisPosX.setUpperBound and
AxisPosY.setUpperBound

**Comment by Leo428** [comment]
Thank you very much!

**Comment by blake1029384756** [comment]
You're Welcome!
