### ISSUE TITLE
Menu buttons don't work

### ISSUE THREAD

**Issue by jonathanmi6** [vannaka/Motion_Profile_Generator#38]
The menu buttons open, save as, and import don't work. Clicking on them doesn't do anything. Also, on lower resolution monitor the window around the application cuts off part of the application which means the menu and some points are not accessable.

Also, this issue has occured on multiple different computers with JDK 1.8.

**Comment by blake1029384756** [comment]
@jonathanmi6 can you please build from the dev branch and try again. Also you can run the app from the command line using "Java -jar filename.jar". Any exceptions thrown while clicking those buttons will appear in the console.

As for the low resolution displays, we know.

**Comment by jonathanmi6** [comment]
I don't usually do code so forgive my ignorance, but how do you build the project in VSCode? Or do I need to use some other IDE?

As for running the 3.0.0 .jar release from command line, when I click on the "Save As" button once it throws these errors: 
![image](https://user-images.githubusercontent.com/34979278/45197538-af027a80-b216-11e8-86c2-76c57f67f43a.png)

**Comment by blake1029384756** [comment]
open the command line to the root of the project and run ./gradle build. That error looks like it will be resolved in the dev branch

**Comment by jonathanmi6** [comment]
I have opened a commandline window in the dev branch folder but entering ./gradle build doesn't work and running the build.gradle file in command line doesn't work either.

**Comment by blake1029384756** [comment]
https://drive.google.com/open?id=1KmTUuz9i3lGqMsJiuREWk-GuqCuVAmik

Here is the built file for now. Just try "gradle build" if that doesnt work you probably dont have gradle installed on your system

**Comment by jonathanmi6** [comment]
The file doesn't work, it does the same thing as before. I installed gradle and when I do gradle build it says that there are deprecated gradle features that are not compatible with gradle 5.0.

**Comment by blake1029384756** [comment]
We use gradle 4.9. Can you post the error from the latest app?

**Comment by jonathanmi6** [comment]
![image](https://user-images.githubusercontent.com/34979278/45199129-f4c34100-b21e-11e8-9b8f-42fa00c61d0a.png)

**Comment by blake1029384756** [comment]
can you open this file : C:\Users\name\.motion-profile-generator\mpg.properties and see if the value for file.workingdir is a valid folder path.

**Comment by jonathanmi6** [comment]
I dont see a mpg.properties file

**Comment by blake1029384756** [comment]
Does the .motion-profile-generator folder exist?

**Comment by jonathanmi6** [comment]
Oh my bad I was looking in the wrong place, I'm assuming the file.workingdir should be the folder where the .jar file is?

**Comment by vannaka** [comment]
Go ahead and delete the .motion-profile-generator directory and then compile and run the latest code from the dev branch. This should fix your issue.

Build command:
    ./gradlew build

Run command:
   java -jar build/libs/Motioni_Profile_Generator-v3.0.0.jar

Both commands executed from the root of the project, i.e. where the build,gradle script is located.

**Comment by vannaka** [comment]
The file.workingdir property should contain the last folder where the Save As dialog was used.

**Comment by jonathanmi6** [comment]
Here is what it was set as: 
![image](https://user-images.githubusercontent.com/34979278/45232789-7b126e00-b285-11e8-90a7-944fc50fe3f3.png)

I did the steps you said and it is working now! Thank you very much.

**Comment by blake1029384756** [comment]
You're Welcome. Glad we could resolve this for you!
