### ISSUE TITLE
Jar file won't run

### ISSUE THREAD

**Issue by orangeandblack5** [vannaka/Motion_Profile_Generator#4]
Hello! I have downloaded the zipped folder, extracted the files, and attempted to run the jar file, but nothing happens. I uninstalled and re-installed both the JRE and JDK, with no effect. Using a batch file to attempt to run the jar gives the message "no main manifest attribute in pathfinder.jar" in a cmd screen that pops up for roughly a tenth of a second.

Thank you very much for any help!

**Comment by vannaka** [comment]
Could you post the command you used to run the jar?

**Comment by orangeandblack5** [comment]
java -jar pathfinder.jar

Which, to my understanding, should run the jar file. I do not claim to be well-versed in batch files, however.

**Comment by blake1029384756** [comment]
@orangeandblack5 you can't run pathfinder.jar because that isn't our app, it's the pathfinder library. [here]
 (https://github.com/vannaka/Motion_Profile_Generator/releases/tag/v2.0.0)

**Comment by orangeandblack5** [comment]
So how do I find that link on my own? Literally created this GitHub account today lol

**Comment by orangeandblack5** [comment]
Oh, you go to the releases tab. Yay.

My previous GitHub experiences have only involved downloading incomplete code, so I didn't even know that this was a thing.

Thanks a ton, both of you; and, as I expected, I feel kinda dumb now. :P

**Comment by vannaka** [comment]
Np, man. Keep on learning!
