### ISSUE TITLE
Screen Problems

### ISSUE THREAD

**Issue by ebot1234** [vannaka/Motion_Profile_Generator#40]
Hi, so the program doesn't resize properly and I can't access the menus to save or load project files.
Below is a picture of the program running on my computer.
-Ethen
![motion profile problem](https://user-images.githubusercontent.com/27324247/46104867-7d8c2780-c1a2-11e8-8beb-3f838dbcf3c1.jpg)

**Comment by blake1029384756** [comment]
@ebot1234 Which branch are you using? Please try the dev branch if you arent currently

**Comment by ebot1234** [comment]
I was using the master branch, I will switch thanks.

**Comment by blake1029384756** [comment]
@ebot1234 You're Welcome. Is it working now?

**Comment by ebot1234** [comment]
The sizing works. I'm currently using Windows 10. The program doesn't show
the points on the graph after adding them through the side menu.

**Comment by vannaka** [comment]
That's because the Pathfinder lib didn't get loaded correctly. Is it 32 or 64 bit windows?

**Comment by ebot1234** [comment]
64

**Comment by vannaka** [comment]
How did you build the project?

**Comment by ebot1234** [comment]
I used eclipse photon and ran the program through there.

**Comment by vannaka** [comment]
you need to use gradle to build the jar. Open a command prompt in the root project dir, the one with the build.gradle in it, and execute the command "./gradlew build", without quotes.
