### ISSUE TITLE
2019 Deep Space Game

### ISSUE THREAD

**Issue by jasondaming** [vannaka/Motion_Profile_Generator#44]
Do you have plans to change other things for the 2019 game (Deep Space)?

I am pretty sure we can just load a 2019 picture and things will work just fine but if you already have one or are planning to make that change then I will hold off

**Comment by blake1029384756** [comment]
@jasondaming You are correct. You can just load in a 2019 picture. It needs to have a 54:27 aspect ratio for measurements to be correct.

**Comment by vannaka** [comment]
We're exhausted from Ri3D. Should be updated with a new image in a few days.

**Comment by jasondaming** [comment]
@vannaka @blake1029384756 Here is the picture I made let me know if this looks right! (1134x567)
![frc2019 deep space](https://user-images.githubusercontent.com/15695521/50854110-c929a200-1349-11e9-9751-db2225e25569.jpg)

**Comment by blake1029384756** [comment]
@jasondaming Perfect! Thank you
