### ISSUE TITLE
Position Graph Size 

### ISSUE THREAD

**Issue by AustinRobinson** [vannaka/Motion_Profile_Generator#45]
How can I change the actual size of the position graph, not the scale of each axis?

**Comment by blake1029384756** [comment]
You can change the axis ticks in the updateAxis method here:

Motion_Profile_Generator/src/java/com/mammen/ui/javafx/main/graphs/PosGraphController.java

**Comment by AustinRobinson** [comment]
Got it, Thanks.

**Comment by vannaka** [comment]
If you add a feature to change the size while the app is running then please submit a pull request.

**Comment by AustinRobinson** [comment]
Ok. If I get time to get around to it I can reopen this issue and submit a pull request.
