### ISSUE TITLE
Scaling Issues

### ISSUE THREAD

**Issue by ThomasCrund** [vannaka/Motion_Profile_Generator#46]
Hi Got the latest update of the app and i appear to have some scaling issues it seems like it says the field is only 10 meters long and i know this is wrong.

![screen shot 2019-01-21 at 12 15 32 pm](https://user-images.githubusercontent.com/39323104/51447889-558a8a80-1d76-11e9-9873-4a4e8e30806a.png)

**Comment by vannaka** [comment]
Are the other units correct?

**Comment by ThomasCrund** [comment]
![screen shot 2019-01-21 at 12 20 41 pm](https://user-images.githubusercontent.com/39323104/51447951-fe38ea00-1d76-11e9-98bd-e1f89a80ce20.png)
Nope

**Comment by vannaka** [comment]
Issue fixed in release [v4.0.1](https://github.com/vannaka/Motion_Profile_Generator/releases/tag/v4.0.1).
