### ISSUE TITLE
[Enhancement] Export profiles as C++ or Java arrays.

### ISSUE THREAD

**Issue by vannaka** [vannaka/Motion_Profile_Generator#5]
Instead of exporting as a CSV export a text file with either a java or c++ array so that it can be copied into code and not have to be read in from a file. Maybe put in a File->Export->C++ or Java Dropdown menu.

**Comment by sciencewhiz** [comment]
Here's another way to do it, for Java: https://www.chiefdelphi.com/forums/showthread.php?threadid=165151
