### ISSUE TITLE
[Enhancement] Add ability to choose the generation method. Cubic or Quintic

### ISSUE THREAD

**Issue by blake1029384756** [vannaka/Motion_Profile_Generator#7]
Right now the default is to use the cubic method. We will add the ability to choose between cubic and quintic

**Comment by blake1029384756** [comment]
Added in [9d696af](https://github.com/vannaka/Motion_Profile_Generator/commit/9d696af43216819ce5f95fdd2bedfac3cdad3a73)

**Comment by GaganBhat** [comment]
Can anyone tell me the difference between cubic and quintic?

**Comment by blake1029384756** [comment]
@gaganbhat I would suggest you ask over on Jaci's GitHub. I know they are two different ways of generating the splines between the points but I have not studied the math behind profile generation so I cannot give you an answer.

**Comment by vannaka** [comment]
It refers to the degree of the polynomial equation used to fit a path between the points provided. Cubic is in the form Ax^3+Bx^2+Cx+D and quintic adds Ex^5+Fx^4 to it. As far as which is better, it depends. It mainly affects the angles throughout the path. Just mess with each and choose one you like the best.
