### ISSUE TITLE
Loading profiles in 2.2 when created in 2.1

### ISSUE THREAD

**Issue by sriharis123** [vannaka/Motion_Profile_Generator#8]
Hello, our team generated all of our profiles on your 2.1 release and while transferring to 2.2 we noticed that instead of the profile loading into the list, it instead loaded into wheel base depth. Can they be loaded into the list instead so that we don't have to remake all of our profiles?

**Comment by blake1029384756** [comment]
That's because we read the first 7 lines in the .bot file for the motion variables and anything after that is a waypoint. So you are missing the Wheel Base D variable in line 6. To fix this just edit the .bot file and add this line as 0.0
[Example](https://imgur.com/a/uaJvV)

**Comment by sriharis123** [comment]
Got it, thanks.
