### ISSUE TITLE
[Enhancement] Add support for other units of measure

### ISSUE THREAD

**Issue by Drewsapple** [vannaka/Motion_Profile_Generator#9]
Support inputs and profile generation in other units of measure (meters, inches etc.) possibly selected via a dropdown menu.

**Comment by blake1029384756** [comment]
Thanks for the suggestion. We will definitely get this implemented!

**Comment by theopolisme** [comment]
👍 Support for meters would be great, especially to match `robotpy-pathfinder`'s standard setup!

**Comment by blake1029384756** [comment]
I have added this feature in the latest version 2.3.0! 

At the current time I have decided to just use feet and meters because inches and centimeters seem to small when the robots move so far
